# Summary

Here we attempt to build a classification model using the `Random Forest Classifier` algorithm [@randomforest] which will use the `Census Income` data with demographic features such as level of education, age, hours dedicated to work, etc to predict whether a person’s annual income will be greater than 50K or not. Our model was able to correctly predict 83% of the test examples. Our classifier performed fairly on unseen test data with an `ROC AUC` score of 0.89, indicating that it is able to distinguish between the positive class (income > 50k) and negative class (income <=50K) with 0.89 probability. The average `precision` score of our model on the test data is 0.70 and `recall` score is close to 0.71, indicating that among the people whose income is actually >50K, we identified 70% of them correctly and among all the people who earned more than 50K, we were able to predict 71% of them correctly. However, it incorrectly predicted 0.064% test examples as `false positives`. These kinds of incorrect predictions could lead people into believing that they can earn more than 50K by following some other career path which might not be favourable for them, thus we recommend continuing the study to improve this prediction model before it is put into production.
