# Introduction

As we progress into the future, it has become imperative to earn high to be able to lead a good lifestyle along with enjoying luxuries. People are curious to know what they can do to earn more, or in which phase of their life that period will come, where they will be earning the highest in their careers. 

Sometimes people are not sure how the level of schooling, the number of hours they dedicate to their work, their marital status  and some other factors affect their annual income. To determine this, here we ask if we can use a machine learning algorithm to predict whether a person will earn more than 50K annually based on factors like the education level, age, hours worked and many more. Having an understanding of whether they will be able to earn more than 50K based on some factors, can help people tweak their career decisions early in life and come up with a plan that can help them earn more in future. [@chakrabarty2018statistical] Thus, if a machine learning algorithm can accurately and effectively predict whether a person will earn more than 50K annually,  this could help people make better decisions early in their life, until things go out of their hands.
