# Findings 
### Feature Transformation
From the EDA, it is discovered that most of the values in the column `native_country` are `United-States`, while each of the other values have a very little proportion and hard for the model to derive information. Therefore we transformed the `native_country` feature into a binary feature, where `True` stands for the person comes from the US, `False` for the rest.  

To transform the data frame into a ready-to-use array for the machine learning model, we have used a column transformer. In particular, we apply scaling to numeric feautres, one-hot encoding to categorical features, and binary encoding to binary features. However, from EDA, we also know that there are null values in two of the categorical features `workclass` and `occupation`. As it does not make sense to impute any category to the missing value, we decided not to encode the null value class, i.e. the one-hot encoding for null would be all zero. Furthermore, `education`, `race`, `capital_gain` and `capital_loss` are dropped. It is because `education_num` is already the ordinal encoding of `education`, we do not want to duplicate the information, and `race` shall not be considered due to ethical controversy. Also, it is found that `capital_gain` and `capital_loss` are mostly zero-valued, that little information could be exploited, so we decided to drop these columns to simplify the features.

## Model Training
// Choose Random Forest

// Baseline

// Metric used & Hyperparameter Tuning

# Results
## Metrics