# Further Development

To further improve the prediction result in the future, there are a few different approaches we could try.

First we could try different types of classification models. One model we would try is support vector machine (SVM) with RBF kernel since it could transform the features to hyperplanes with higher dimension, which could possibly discover a better decision boundary for the predictive problem. Another model we would want to try is multi-layer perceptron, i.e. a simple neural network. As it introduces non-linearity transformation to the output of each perceptron, the overall model would have a higher degree of freedom, thus might be able to formulate a better decision rule for the classification.

Another approach would be feature selection and feature engineering In our analysis, some of the features are dropped due to a bad distribution but they might also contain import information. For instance, we could transform `capital_gain` and `capital_loss` into ordinal categorical features, or group `native_country` by continents. After that, we could also generate feature with higher power, and make use of RFE algorithm to select features with top importance and try to boost the performance of the model.
